# Generated by Django 5.0.1 on 2024-01-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
