# Generated by Django 5.0.1 on 2024-01-24 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=100, verbose_name='Группа анализов')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Групппа анализов',
                'verbose_name_plural': 'Грууппы анализов',
            },
        ),
        migrations.CreateModel(
            name='NameOfExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название исследования')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Название исследования',
                'verbose_name_plural': 'Названия исследований',
            },
        ),
        migrations.CreateModel(
            name='NameOfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название анализа')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_name', to='exams.groupofanalysis', verbose_name='Группа анализов')),
            ],
            options={
                'verbose_name': 'Название анализа',
                'verbose_name_plural': 'Названия анализов',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Дата анализа', verbose_name='Дата')),
                ('value', models.CharField(help_text='Значение', max_length=10, verbose_name='значение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_name', to='exams.nameofanalysis', verbose_name='Название анализа')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Дата исссследования', verbose_name='Дата')),
                ('content', models.TextField(help_text='Заключение', verbose_name='Выводы')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_name', to='exams.nameofexam', verbose_name='Название исследования')),
            ],
        ),
    ]
