# Generated by Django 5.0.1 on 2024-01-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_analysis_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото исследования'),
        ),
    ]
